var client = {
    // The paths for our EPUB assets
    paths: {
        client_js: '../../../js',
        client_css: '../../../css'
    },
    // The required modules for our EPUB assets
    required: [
        'client_js/libs/modernizr.min',
        'client_js/libs/jquery.easing.1.3.min',
        'client_js/libs/jquery.fitvids',
        'client_js/script',
        'css!client_css/base.css',
/*
        'css!client_css/demo_bar.css',
        'css!client_css/themes/type_05.css',
        'css!client_css/themes/type_02.css',
        'css!client_css/themes/type_03.css',
        'css!client_css/themes/type_04.css',
        'css!client_css/themes/type_05.css',
        'css!client_css/themes/type_06.css',
        'css!client_css/themes/type_07.css',
        'css!client_css/themes/type_08.css',
        'css!client_css/themes/type_09.css',
        'css!client_css/themes/type_10.css',
        'css!client_css/themes/type_11.css',
        'css!client_css/themes/type_12.css',
        'css!client_css/themes/type_13.css',
        'css!client_css/themes/type_14.css',
        'css!client_css/themes/type_15.css',
        'css!client_css/themes/type_16.css',
        'css!client_css/themes/type_17.css',
        'css!client_css/themes/type_18.css',
        'css!client_css/themes/type_19.css',
        'css!client_css/themes/type_20.css',
        'css!client_css/themes/type_101.css',
        'css!client_css/themes/color_01.css',
        'css!client_css/themes/color_02.css',
        'css!client_css/themes/color_03.css',
        'css!client_css/themes/color_04.css',
        'css!client_css/themes/color_05.css',
        'css!client_css/themes/color_06.css',
*/
        'css!client_css/themes/color_07.css'
/*        ,
        'css!client_css/themes/color_08.css',
        'css!client_css/themes/color_09.css',
        'css!client_css/themes/color_10.css',
        'css!client_css/themes/color_11.css',
        'css!client_css/themes/color_12.css',
        'css!client_css/themes/color_13.css',
        'css!client_css/themes/color_14.css',
        'css!client_css/themes/color_15.css',
        'css!client_css/themes/color_16.css',
        'css!client_css/themes/color_17.css',
        'css!client_css/themes/color_18.css',
        'css!client_css/themes/color_19.css',
        'css!client_css/themes/color_20.css',
        'css!client_css/themes/color_21.css',
        'css!client_css/themes/color_22.css',
        'css!client_css/themes/color_23.css',
        'css!client_css/themes/color_24.css',
        'css!client_css/themes/color_25.css',
        'css!client_css/themes/color_26.css',
        'css!client_css/themes/color_27.css',
        'css!client_css/themes/color_28.css',
        'css!client_css/themes/color_29.css'
*/
    ]
};